services:
  - type: web
    name: pay-later-balance
    env: node
    plan: free
    branch: main
    rootDir: .
    buildCommand: |
      cd $RENDER_PROJECT_ROOT
      npm install
    startCommand: |
      cd $RENDER_PROJECT_ROOT
      npm start
    envVars:
      - key: SHOPIFY_ADMIN_API_TOKEN
        sync: false
