name = "Pay Later Balance App v2"
client_id = "c9f38f889b5dcf75a81696b7c44d5ba"
application_url = "https://pay-later-balance-z555.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "0fme0w-es.myshopify.com"

[auth]
redirect_urls = [
  "https://pay-later-balance-z555.onrender.com/auth/callback",
  "https://pay-later-balance-z555.onrender.com/auth/shopify/callback"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false
