name = "Pay Balance Extension"
handle = "pay-balance-extension"
type = "customer_account_ui_extension"

[[extension_points]]
target = "customer-account.order-details.block.render"

[build]
command = "echo 'no build needed'"
