type = "ui_extension"
name = "Pay Balance Extension"
[[extension_points]]
target = "customer-account.order-details.block.render"
module = "./src/index.jsx"

[build]
command = "echo 'no build needed'"

