name = "Pay Balance Extension"
type = "customer_accounts_ui_extension"
handle = "pay-balance-extension"

[[extension_points]]
target = "customer-account.order-details.block.render"

[build]
command = "echo 'no build needed'"
